apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: poolcontributions.angler-dex.github.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: angler-dex.github.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cpu: # 200m
                  type: string
                memory: # 128Mi
                  type: string
                location: # dn5bpsbw
                  type: string
                secretQuantity:
                  type: integer
                secretPriceFunc:
                  type: string
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: poolcontributions
    singular: poolcontribution
    kind: PoolContribution
    shortNames:
    - poolc
